---

- name: Installer restic, lftp
  package: name=restic,lftp

- name: Creer le dossier home ?
  file:
    state: directory
    path: '{{ home }}'
    mode: '0700'

- name: Installer le backup password
  when: lookup('env', 'RESTIC_PASSWORD')
  copy:
    content: '{{ lookup("env", "RESTIC_PASSWORD") }}'
    dest: '{{ home }}/.restic_password'
    mode: '0400'

- name: Initializer le repo de backup
  register: restic_init
  changed_when: "'created restic repo' in restic_init['stdout']"
  shell: |
    export RESTIC_PASSWORD_FILE={{ home }}/.restic_password
    export RESTIC_REPOSITORY={{ lookup('env', 'RESTIC_REPOSITORY') or home + '/restic' }}
    test -d $RESTIC_REPOSITORY || restic init

- name: Executer le script de backup
  when: "'created restic repo' not in restic_init['stdout']"
  shell: '{{ home }}/backup.sh'

- name: Installer le script de backup
  when: lookup('env', 'RESTIC_PASSWORD')
  template:
    src: backup.sh
    dest: '{{ home }}/backup.sh'

- name: Installer le cron de backup
  when: lookup('env', 'RESTIC_PASSWORD')
  include_role: name=yourlabs.timer
  vars:
    name: '{{ home.split("/")[-1] }}-backup'
    cmd: '{{ home }}/backup.sh'
    chdir: '{{ home }}'
    oncalendar: '*-*-* 23:00:00'
